// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ualboikmyquaiupdwtev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhbGJvaWtteXF1YWl1cGR3dGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjkzMjMsImV4cCI6MjA3MTc0NTMyM30.p_ReJb25A_SIHdzw2mh_ZcrFvwVy0GX1P-mRdLFnG8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});